export const HELP_DATA_STORAGE_KEY = "AHD_HELP_DATA";
export const TOUR_DATA_STORAGE_KEY = "AHD_TOUR_DATA";
export const HIGHLIGHTS_DATA_STORAGE_KEY = "AHD_HIGHLIGHTS_DATA";
export const AHD_VISITOR_STATS_STORAGE_KEY = "AHD_VISITOR_STATS";
